const os = require('os');
console.log(os.platform());
console.log(os.type());
console.log(os.hostname());
console.log(os.arch());
console.log(os.release());
console.log(os.cpus());
console.log(os.freemem());
console.log(os.totalmem());
console.log(os.homedir());